import { useState } from 'react';
import axios from 'axios';

function App() {
  const [input, setInput] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleGenerateImage = async () => {
    setLoading(true);
    setError('');
    setImageUrl('');

    try {
      const res = await axios.post(
        'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyAo_H2fkN00fjm-sQkU2t2EdNDeSlx9Zeg',
        {
          prompt: input,
          n: 1,
          size: '512x512',
        },
        {
          headers: {
            'Content-Type': 'application/json',
            Authorization: `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyAo_H2fkN00fjm-sQkU2t2EdNDeSlx9Zeg`, // МҰНДА API КІЛТІҢІЗДІ ҚОЙЫҢЫЗ
          },
        }
      );

      const url = res.data.data[0].url;
      setImageUrl(url);
    } catch (err) {
      console.error(err);
      setError('Қате орын алды. API кілт дұрыс па немесе лимиттен асып кетті ме?');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-100 to-white p-6">
      <h1 className="text-3xl font-bold mb-4">🖼 AI Сурет Генерациясы</h1>
      <textarea
        className="w-full border p-2 rounded mb-4"
        rows={4}
        placeholder="Мысалы: қызыл фондағы 3D стильдегі робот"
        value={input}
        onChange={(e) => setInput(e.target.value)}
      />
      <button
        onClick={handleGenerateImage}
        className="px-4 py-2 bg-green-500 text-white rounded"
        disabled={loading}
      >
        {loading ? 'Сурет жасалуда...' : 'Сурет жасау'}
      </button>

      {error && <div className="mt-4 text-red-500">{error}</div>}

      {imageUrl && (
        <div className="mt-6">
          <img src={imageUrl} alt="Generated by AI" className="rounded shadow-md" />
        </div>
      )}
    </div>
  );
}

export default App;
